# 1. Образ з Python 3.11
FROM python:3.11-slim

# 2. Встановлюємо системні залежності
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gfortran \
    ffmpeg \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# 3. Робоча директорія
WORKDIR /app

# 4. Копіюємо requirements і ставимо пакети
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# 5. Копіюємо код бекенду
COPY . .

# 6. Вказуємо порт і команду запуску
EXPOSE 8000
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:8000", "--workers", "4"]