services:
  - type: web
    name: mymusicmind
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mymusicmind
          property: connectionString
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        sync: false
      - key: LASTFM_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000

databases:
  - name: mymusicmind
    plan: free
